accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy


app_name='accounts'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.CustomLoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('update-student/<int:user_id>/', views.StudentUpdateView.as_view(), name='update_student'),
]

main/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import user_passes_test
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'classrooms', views.ClassroomViewSet)
router.register(r'name-id-tests', views.NameIdTestViewSet)
router.register(r'test-questions', views.TestQuestionViewSet, basename='test-questions')
router.register(r'options', views.OptionViewSet)
router.register(r'users', views.CustomUserViewSet)
router.register(r'maxscore', views.MaxScoreViewSet)
router.register(r'classroomrequest', views.ClassroomRequestViewSet)



def is_superuser(user):
    return user.is_superuser


app_name='main'
urlpatterns = [
    path('api/', include(router.urls)),
    path('signup/student/', views.StudentSignUpView.as_view(), name='student_signup'),
    path('signup/teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('', views.ProfilePageView.as_view(), name='profile'),
    path('portfolio/', views.PortfolioView.as_view(), name='portfolio'),
    path('classroom_accept/<int:pk>/', views.ClassroomAcceptView.as_view(), name='classroom_accept'),
    path('join_classroom/', views.ClassroomJoinView.as_view(), name='join_classroom'),
    path('update/profile/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('remove/account/<int:pk>/', views.AccountRemoveView.as_view(), name='delete_account'),
    path('classroom/create/', views.ClassroomCreateView.as_view(), name='classroom_create'),
    path('test/create/', views.TestCreateView.as_view(), name='test_create'),
    path('test/<int:pk>/delete/', views.TestDeleteView.as_view(), name='test_delete'),
    path('question/<int:pk>/create/', views.QuestionCreateView.as_view(), name='question_create'),
    path('option/<int:pk>/create/', views.OptionCreateView.as_view(), name='option_create'),
    path('score/<int:pk>/record/', views.ScoreRecordView.as_view(), name='record_score'),
    path('final/<str:category>/score/', views.FinalScoreView.as_view(), name='final_score'),
    path('question/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='question_delete'),
    path('option/<int:pk>/delete/', views.OptionDeleteView.as_view(), name='option_delete'),
    path('test-classroom/<int:pk>/', views.TestClassroomView.as_view(), name='test-classroom'),
    path('character_silence/', views.ClassroomSilenceView.as_view(), name='character_voice'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models





class CustomUser(AbstractUser):
    total_max_scores = models.FloatField(default=0)
    total_japanese_score = models.FloatField(default=0.0)
    total_english_5_score = models.FloatField(default=0.0)
    total_english_6_score = models.FloatField(default=0.0)
    total_phonics_score = models.FloatField(default=0.0)
    total_numbers_score = models.FloatField(default=0.0)
    total_eiken_score = models.FloatField(default=0.0)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from main.models import Teacher, Student, Classroom
from django.contrib.auth.forms import AuthenticationForm
from django.utils.crypto import get_random_string

class CustomAuthenticationForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザネーム'
        self.fields['username'].label = 'ユーザネーム'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワード'
        self.fields['password'].label = 'パスワード'

class TeacherSignUpForm(forms.ModelForm):
    username = forms.CharField(
        label="ユーザー名",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    
    last_name = forms.CharField(
        label="名字",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'password', 'last_name')

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data


class StudentSignUpForm(forms.ModelForm):
    username = forms.CharField(
        label="ユーザー名",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    last_name = forms.CharField(
        label="名字",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    password = forms.CharField(
        label="パスワード",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    student_number = forms.CharField(
        label="出席番号",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password')
        user.set_password(password)
        if commit:
            user.save()
            student_number = 0
            student_number = self.cleaned_data.get('student_number')
            student = Student.objects.create(user=user, student_number=student_number)
        return user

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

accounts/views.py
import json
from django.http import JsonResponse
from django.views import View
from django.shortcuts import get_object_or_404, render, redirect
from .models import CustomUser
from main.models import Student
from django.contrib.auth import authenticate, login
from .forms import CustomAuthenticationForm
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginView(View):
    template_name = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
        form = AuthenticationForm(request)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('main:profile')
            else:
                form.add_error(None, "ユーザーネームまたはパスワードが間違っています。")
                return render(request, self.template_name, {'form': form})

        return render(request, self.template_name, {'form': form})







class StudentUpdateView(View):
    def post(self, request, *args, **kwargs):
        user_id = self.kwargs.get('user_id')
        user = get_object_or_404(CustomUser, pk=user_id)
        student = get_object_or_404(Student, user=user)

        try:
            data = json.loads(request.body)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON data'}, status=400)

        username = data.get('username')
        password = data.get('password')
        student_number = data.get('student_number')

        if username:
            user.username = username
        if password:
            user.set_password(password)
        if student_number:
            student.student_number = student_number

        if CustomUser.objects.filter(username=username).exists():
            return JsonResponse({'error': 'このユーザネームはすでに使われている'}, status=400)

        if len(username) > 10:
            return JsonResponse({'error': 'ユーザーネームは最大１０文字'}, status=400)

        user.save()
        student.save()

        return JsonResponse({
            'message': 'Student info updated successfully',
            'username': user.username,
        })

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログイン</title>
    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous" defer></script>


</head>
<body>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<br>
<br>
<form method="post">
  {% csrf_token %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card-group mb-0">
          <div class="card p-4">
            <div class="card-body">
              <h1>ログイン</h1>
              {% if form.non_field_errors %}
                  <div class="alert alert-danger">
                      {{ form.non_field_errors }}
                  </div>
              {% endif %}
              <div class="input-group mb-3">
                <span class="input-group-addon"><i class="fa fa-user"></i>ユーザネーム：</span>
                {{ form.username }}
              </div>
              <div class="input-group mb-4">
                <div class="input-group-addon"><i class="fa fa-lock"></i>パスワード：</div>
                {{ form.password }}
              </div>
              <div class="row">
                <div class="col-6">
                  <button type="submit" class="btn btn-primary" style="width: 200px; padding: 4px; border: 5px solid black; box-sizing: border-box;">ログイン</button>
                </div>
              </div>
            </div>
          </div>

          <div class="card p-4" style="border: 1px solid black;">
            <div class="card-body text-center">
            　<h3>アカウント登録：</h3>
              <a href="{% url 'main:student_signup' %}">
                <button type="button" class="btn btn-success mb-3" style="width: 200px; border: 5px solid black;">
                  生徒登録！
                </button>
              </a>
              <a href="{% url 'main:teacher_signup' %}">
                <button type="button" class="btn btn-success mb-3" style="width: 200px; border: 5px solid black;">
                  先生登録！
                </button>
              </a>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</form>
</body>
</html>

accounts/templates/accounts/student_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>生徒登録</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script>
        function disableButton() {
            var submitBtn = document.getElementById('submit-btn');
            submitBtn.disabled = true;
            setTimeout(function() {
                submitBtn.disabled = false;
            }, 5000);
        }
    </script>
</head>
<body>
    {% if error_message %}
        <div class="alert alert-danger">{{ error_message }}</div>
    {% endif %}
    <div class="container mt-5">
        <h2>生徒登録！</h2>
        <h4>ユーザーネームは最大長さ１０文字。</h4>
        <form method="post" onsubmit="disableButton()">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.last_name.label_tag }}
                <p>名字は学校の授業で練習する人以外は入れなくても大丈夫</p>
                {{ form.last_name }}
            </div>
            <div class="form-group">
                {{ form.student_number.label_tag }}
                <p>出席番号は学校の授業で練習する人以外は入れなくても大丈夫</p>
                {{ form.student_number }}
            </div>
            <div class="form-group">
                <label for="password">パスワード:</label>
                <input type="password" id="password" name="password" class="form-control">
            </div>
            <button type="submit" id="submit-btn" class="btn btn-primary">登録</button>
        </form>
    </div>
</body>
</html>

accounts/templates/accounts/teacher_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>先生登録</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script>
        function disableButton() {
            var submitBtn = document.getElementById('submit-btn');
            submitBtn.disabled = true;
            setTimeout(function() {
                submitBtn.disabled = false;
            }, 5000);
        }
    </script>
</head>
<body>
    {% if error_message %}
        <div class="alert alert-danger">{{ error_message }}</div>
    {% endif %}
    <div class="container mt-5">
        <h2>先生登録！</h2>
        <h4>ユーザーネームは最大長さ１０文字。</h4>
        <form method="post" onsubmit="disableButton()">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.last_name.label_tag }}
                {{ form.last_name }}
            </div>
            <div class="form-group">
                <label for="password">パスワード:</label>
                <input type="password" id="password" name="password" class="form-control">
            </div>
            <button type="submit" id="submit-btn" class="btn btn-primary">Register</button>
        </form>
    </div>
</body>
</html>